# Generated by Django 5.0.13 on 2025-03-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='changeme', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
