# Generated by Django 5.0.13 on 2025-03-28 18:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0002_userprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('persona', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('api_token', models.CharField(default='default_token', max_length=255)),
                ('last_post', models.DateTimeField(blank=True, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pds_app.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
