# Generated by Django 5.0.13 on 2025-04-04 20:35

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0003_digitaltwin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
