# Generated by Django 5.0.13 on 2025-04-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0004_alter_post_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_bot',
            new_name='is_banned',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_collaborator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_digital_twin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
