# Generated by Django 5.0.13 on 2025-04-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0005_rename_is_bot_userprofile_is_banned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
