# Generated by Django 5.0.13 on 2025-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0012_experimentinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaltwin',
            name='api_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
