# Generated by Django 5.0.13 on 2025-05-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0013_alter_digitaltwin_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='pds_app.post'),
        ),
    ]
