# Generated by Django 5.0.13 on 2025-05-15 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0014_post_repost_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('username', 'experiment')},
        ),
    ]
