# Generated by Django 5.0.13 on 2025-05-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0016_experiment_irb_additions'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
