# Generated by Django 5.0.13 on 2025-09-26 14:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0019_authapitokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthApiTokens',
            new_name='AuthApiToken',
        ),
    ]
