# Generated by Django 5.0.13 on 2025-09-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0019_multitoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multitoken',
            name='name',
        ),
    ]
