# Generated by Django 5.0.13 on 2025-11-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0020_rename_authapitokens_authapitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
