# Generated by Django 5.0.13 on 2025-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0021_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dorm_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
