# Generated by Django 5.0.13 on 2025-11-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0022_userprofile_dorm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
