#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Get the number of CPU cores, default to 2 if not available
CORES=${CPU_CORES:-$(nproc --all 2>/dev/null || echo 2)}

# Calculate the number of Gunicorn workers
WORKERS=$((2 * CORES + 1))

python /app/manage.py collectstatic --noinput

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app --workers "${WORKERS}"
