# Generated by Django 5.0.13 on 2025-04-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_researcher',
            field=models.BooleanField(default=False, help_text='Designates whether this user is a researcher.', verbose_name='is researcher'),
        ),
    ]
