# Generated by Django 5.0.13 on 2025-04-25 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pds_app', '0007_experiment_identifier'),
        ('users', '0002_user_is_researcher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_accessed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pds_app.experiment'),
        ),
    ]
